**1. Import pandas as pd.**

In [2]:
import pandas as pd

In [3]:
from google.colab import files
files.upload()

Saving City_of_Chicago_Payroll_Data.csv to City_of_Chicago_Payroll_Data.csv

{'City_of_Chicago_Payroll_Data.csv': b'Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate\r\n"ALLISON,  PAUL W",LIEUTENANT,FIRE,F,Salary,,"$107,790.00 ",\r\n"BRUNO,  KEVIN D",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"COOPER,  JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,,"$114,324.00 ",\r\n"CRESPO,  VILMA I",STAFF ASST,LAW,F,Salary,,"$76,932.00 ",\r\n"DOLAN,  ROBERT J",SERGEANT,POLICE,F,Salary,,"$111,474.00 ",\r\n"DUBERT,  TOMASZ ",PARAMEDIC I/C,FIRE,F,Salary,,"$91,080.00 ",\r\n"EDWARDS,  TIM P",LIEUTENANT,FIRE,F,Salary,,"$114,846.00 ",\r\n"ELKINS,  ERIC J",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"ESTRADA,  LUIS F",POLICE OFFICER,POLICE,F,Salary,,"$96,060.00 ",\r\n"EWING,  MARIE A",CLERK III,POLICE,F,Salary,,"$53,076.00 ",\r\n"FINN,  SEAN P",FIREFIGHTER,FIRE,F,Salary,,"$87,006.00 ",\r\n"FITCH,  JORDAN M",LAW CLERK,LAW,F,Hourly,35,,$14.51 \r\n"FREELON,  CHERYL N",POLICE OFFICER,POLICE,F,Salary,,"$96,060.00 ",\r\n"GRAFF,  KEVIN M",SERGEANT,POLICE,F,Salary,,"$111,474.00 ",\r\n"GUNN,  ISSAC J",FIREFIGHTER-EMT,FIRE,F,Salary,,"$80,868.00 ",\r\n"HARRIS,  DANIEL J",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"HATTULA,  CARL J",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"HILL,  LATINA P",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"HOLLER,  JOEL P",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"HROMA JR,  JOHN ",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"JACKSON,  ERIC ",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"JOYCE,  SEAN G",CAPTAIN,POLICE,F,Salary,,"$132,876.00 ",\r\n"KING,  WARSHAW ",CAPTAIN-EMT,FIRE,F,Salary,,"$136,794.00 ",\r\n"KWONG,  NORMAN P",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"LEVEK,  NATHAN L",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"MACK,  PAUL C",LIEUTENANT,POLICE,F,Salary,,"$125,190.00 ",\r\n"PETERS,  JOSEPH M",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"MOORE,  TED D",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"SIMON,  JOSEPH G",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"MULLINS,  JOHN T",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"NICOL,  EDWARD R",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"PEASLEE,  SEAN P",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"PESO,  JOANN M",DIR OF NUTRITION,HEALTH,F,Salary,,"$93,876.00 ",\r\n"SPIRES,  WAYNE E",CAPTAIN,FIRE,F,Salary,,"$128,970.00 ",\r\n"RICHARDSON,  BRIAN J",DEPUTY COMMISSIONER,HEALTH,F,Salary,,"$119,772.00 ",\r\n"ROBINSON,  HAROLD ",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"RUIZ,  ERACLIO ",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"SANTOS,  MICHAEL J",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"TOLEDO,  PETER H",SERGEANT,POLICE,F,Salary,,"$101,442.00 ",\r\n"VORTES,  VELMA ",CLERK IV,FIRE,F,Salary,,"$70,092.00 ",\r\n"SKOL,  LARRY W",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"SMITH,  KEVIN W",FIREFIGHTER,FIRE,F,Salary,,"$87,006.00 ",\r\n"STRAKA,  SCOTT M",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"TRAGOS,  THOMAS J",CAPTAIN,FIRE,F,Salary,,"$128,970.00 ",\r\n"VOSBURGH,  GRANT ",PARAMEDIC,FIRE,F,Salary,,"$72,510.00 ",\r\n"VANEK,  AMANDA J",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"VEGA,  ANA L",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"WORD,  HOSEA ",SERGEANT,POLICE,F,Salary,,"$107,988.00 ",\r\n"YARLING,  ZACHARY ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"AARON,  JEFFERY M",SERGEANT,POLICE,F,Salary,,"$101,442.00 ",\r\n"AARON,  KARINA ",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"AARON,  KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,,"$97,056.00 ",\r\n"ABAD JR,  VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,,"$110,064.00 ",\r\n"ABARCA,  ANABEL ",SENIOR POLICY ANALYST,HEALTH,F,Salary,,"$79,284.00 ",\r\n"ABASCAL,  REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20,,$19.66 \r\n"ABBASI,  CHRISTOPHER ",STAFF ASST TO THE ALDERMAN,CITY COUNCIL,F,Salary,,"$50,436.00 ",\r\n"ABBATACOLA,  ROBERT J",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40,,$46.10 \r\n"ABBATE,  JOSEPH L ",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"ABBATEMARCO,  JAMES J",FIRE ENGINEER-EMT,FIRE,F,Salary,,"$103,350.00 ",\r\n"ABBATE,  TERRY M",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ABBOTT,  BETTY L",FOSTER GRANDPARENT,FAMILY & SUPPORT,P,Hourly,20,,$2.65 \r\n"ABBRUZZESE,  WILLIAM J",INVESTIGATOR - IPRA II,IPRA,F,Salary,,"$76,152.00 ",\r\n"ABDALLAH,  ZAID ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"ABDELHADI,  ABDALMAHD ",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ABDELLATIF,  AREF R",FIREFIGHTER (PER ARBITRATORS AWARD)-PARAMEDIC,FIRE,F,Salary,,"$102,228.00 ",\r\n"ABDELMAJEID,  AZIZ ",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ABDOLLAHZADEH,  ALI ",FIREFIGHTER/PARAMEDIC,FIRE,F,Salary,,"$91,272.00 ",\r\n"ABDUL-KARIM,  MUHAMMAD A",ENGINEERING TECHNICIAN VI,WATER MGMNT,F,Salary,,"$111,492.00 ",\r\n"ABDULLAH,  DANIEL N",FIREFIGHTER-EMT,FIRE,F,Salary,,"$95,484.00 ",\r\n"ABDULLAH,  KEVIN ",LIEUTENANT,FIRE,F,Salary,,"$114,846.00 ",\r\n"ABDULLAH,  LAKENYA N",CROSSING GUARD,OEMC,P,Hourly,20,,$17.50 \r\n"ABDULLAH,  RASHAD ",ELECTRICAL MECHANIC-AUTO-POLICE MTR MNT,GENERAL SERVICES,F,Hourly,40,,$46.10 \r\n"ABDULSATTAR,  MUDHAR ",CIVIL ENGINEER II,WATER MGMNT,F,Salary,,"$63,480.00 ",\r\n"ABDUL-SHAKUR,  TAHIR ",GENERAL LABORER - DSS,STREETS & SAN,F,Hourly,40,,$20.77 \r\n"ABEJERO,  JASON V",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ABERCROMBIE IV,  EARL S",PARAMEDIC I/C,FIRE,F,Salary,,"$78,792.00 ",\r\n"ABERCROMBIE,  TIMOTHY ",MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"ABIOYE,  ADEWOLE A",LIBRARY ASSOCIATE - HOURLY,PUBLIC LIBRARY,P,Hourly,20,,$25.10 \r\n"ABNEY,  PATRICK ",POLICE OFFICER,POLICE,F,Salary,,"$72,510.00 ",\r\n"ABOUELKHEIR,  HASSAN A",SENIOR PROGRAMMER/ANALYST,FAMILY & SUPPORT,F,Salary,,"$110,064.00 ",\r\n"ABRAHAM,  GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,,"$110,064.00 ",\r\n"ABRAHAM,  GODWIN K",ENGINEERING TECHNICIAN V,BUSINESS AFFAIRS,F,Salary,,"$101,592.00 ",\r\n"ABRAHAM,  NANCY A",POLICE OFFICER,POLICE,F,Salary,,"$76,266.00 ",\r\n"ABRAM,  ANTHONY A",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"ABRAMAVICIUS,  ANNA A",SUPERVISING TRAFFIC CONTROL AIDE,OEMC,F,Salary,,"$60,852.00 ",\r\n"ABRAMS,  DANIELLE T",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"ABRAMSKI,  JOHN E",AMBULANCE COMMANDER,FIRE,F,Salary,,"$128,970.00 ",\r\n"ABRAMSON,  NICHOLAS ",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"ABRAMS,  SAMUEL A",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"ABRATANSKI,  MARK A",FIREFIGHTER-EMT,FIRE,F,Salary,,"$89,148.00 ",\r\n"ABREU,  DILAN ",SEWER BRICKLAYER,WATER MGMNT,F,Hourly,40,,$44.88 \r\n"ABREU,  EDWIN ",TREE TRIMMER,STREETS & SAN,F,Hourly,40,,$37.25 \r\n"ABREU,  ROBERTO J",TRAFFIC SIGNAL REPAIRMAN,TRANSPORTN,F,Salary,,"$101,712.00 ",\r\n"ABREU,  ROSITA ",PERSONAL COMPUTER OPERATOR III,HEALTH,F,Salary,,"$70,092.00 ",\r\n"ABREU,  VICTOR ",FIREFIGHTER-EMT,FIRE,F,Salary,,"$99,324.00 ",\r\n"ABRON,  FLOYD ",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ABRONS,  KENNETH L",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40,,$46.10 \r\n"ABUBAKER,  MOHAMMED G",SENIOR ENVIRONMENTAL INSPECTOR,HEALTH,F,Salary,,"$80,568.00 ",\r\n"ABUDAYEH,  ELIAS ",POLICE OFFICER,POLICE,F,Salary,,"$72,510.00 ",\r\n"ABUHASHISH,  AWWAD ",PLUMBER,WATER MGMNT,F,Hourly,40,,$48.25 \r\n"ABURIZEG,  MOHAMMAD ",POLICE OFFICER,POLICE,F,Salary,,"$68,616.00 ",\r\n"ABUTALEB,  AHMAD H",CIVIL ENGINEER II,WATER MGMNT,F,Salary,,"$92,388.00 ",\r\n"ABUZANAT,  ABDALLA H",POLICE OFFICER (ASSIGNED AS EVIDENCE TECHNICIAN),POLICE,F,Salary,,"$94,524.00 ",\r\n"ACCARDO,  ANTHONY D",CONSTRUCTION LABORER,AVIATION,F,Hourly,40,,$40.20 \r\n"ACCARDO,  ANTHONY V",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"ACCARDO,  JENNIFER A",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ACCARDO,  THOMAS J",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACCIARI,  MICHAEL G",DIVISION SUPERINTENDENT,STREETS & SAN,F,Salary,,"$117,660.00 ",\r\n"ACCIARI,  NICHOLAS B",MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$36.13 \r\n"ACCURSO,  MARY K",PRESS AIDE I,MAYOR\'S OFFICE,F,Salary,,"$66,300.00 ",\r\n"ACEVEDO,  AARON F",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ACEVEDO,  ALEJANDRO R",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ACEVEDO,  BIENVENIDO ",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACEVEDO,  DAVID M",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"ACEVEDO,  EDWARD ",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ACEVEDO,  EDWIN C",FIREFIGHTER,FIRE,F,Salary,,"$97,386.00 ",\r\n"ACEVEDO,  ERIC ",POLICE OFFICER,POLICE,F,Salary,,"$72,510.00 ",\r\n"ACEVEDO,  GILBERT ",LIEUTENANT-EMT,FIRE,F,Salary,,"$121,818.00 ",\r\n"ACEVEDO,  ILIA ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"ACEVEDO,  JANETE ",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ACEVEDO,  JASON M",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ACEVEDO,  JAVIER ",ASPHALT LABORER,TRANSPORTN,F,Hourly,40,,$40.20 \r\n"ACEVEDO,  JEFF ",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ACEVEDO,  JOSUE ",POLICE COMMUNICATIONS OPERATOR II,OEMC,F,Salary,,"$54,708.00 ",\r\n"ACEVEDO,  MANUEL A",FIREFIGHTER,FIRE,F,Salary,,"$93,666.00 ",\r\n"ACEVEDO,  MARCO A",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$100,980.00 ",\r\n"ACEVEDO,  MARISOL ",SENIOR PUBLIC INFORMATION OFFICER,BUSINESS AFFAIRS,F,Salary,,"$93,300.00 ",\r\n"ACEVEDO,  MARTIN J",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACEVEDO,  MIKE ",AVIATION SECURITY OFFICER,AVIATION,F,Salary,,"$66,792.00 ",\r\n"ACEVEDO,  NADINE M",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACEVEDO,  RAFAEL ",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACEVEDO,  STEVEN A",POOL MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40,,$28.48 \r\n"ACEVES,  JUAN C",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ACEVEZ,  ANTHONY E",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACHILLES,  AMBER L",CHIEF ASST CORPORATION COUNSEL,LAW,F,Salary,,"$127,068.00 ",\r\n"ACHILLY,  LISA S",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ACHTEL,  SCOTT R",FIREFIGHTER-EMT,FIRE,F,Salary,,"$95,484.00 ",\r\n"ACKERMANN,  MICHAEL A",PARAMEDIC I/C,FIRE,F,Salary,,"$78,792.00 ",\r\n"ACKLIN,  QIANA D",CROSSING GUARD,OEMC,P,Hourly,20,,$17.50 \r\n"ACOSTA,  JAIME A",POLICE OFFICER,POLICE,F,Salary,,"$68,616.00 ",\r\n"ACOSTA,  JESSE A",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ACOSTA,  MARK ",POLICE OFFICER,POLICE,F,Salary,,"$68,616.00 ",\r\n"ACOSTA,  MARTHA A",LIBRARY ASSOCIATE,PUBLIC LIBRARY,F,Salary,,"$69,492.00 ",\r\n"ACOSTA,  MICHELE D",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ACOSTA,  NATALIE ",POLICE OFFICER,POLICE,F,Salary,,"$68,616.00 ",\r\n"ACOSTA,  PABLO S",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"ACOSTA,  ROSA M",PARKING ENFORCEMENT AIDE,AVIATION,F,Salary,,"$60,852.00 ",\r\n"ACRES,  ANTHONY E",CONSTRUCTION LABORER,GENERAL SERVICES,F,Hourly,40,,$40.20 \r\n"ACSVECS,  ZAIREH ",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ADAIR,  KENNETH R",POLICE OFFICER (ASGND AS MARINE OFFICER),POLICE,F,Salary,,"$91,338.00 ",\r\n"ADAIR,  STEVEN ",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"ADAMCZYK JR,  JAN ",BOOTER - PARKING,FINANCE,F,Hourly,40,,$32.25 \r\n"ADAMCZYK,  LAWRENCE M",FIREFIGHTER,FIRE,F,Salary,,"$93,666.00 ",\r\n"ADAME,  PEDRO ",CUSTODIAL WORKER,AVIATION,F,Hourly,40,,$21.20 \r\n"ADAMIAK,  SIMON P",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ADAMIK,  JEFFREY S",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$100,980.00 ",\r\n"ADAMIK,  MATTHEW W",FIREFIGHTER/PARAMEDIC,FIRE,F,Salary,,"$91,272.00 ",\r\n"ADAM,  MICHAEL A",MOTOR TRUCK DRIVER,TRANSPORTN,F,Hourly,40,,$35.60 \r\n"ADAMOW,  JEFFREY W",FIREFIGHTER-EMT,FIRE,F,Salary,,"$89,148.00 ",\r\n"ADAMS,  CRAIG W",POLICE OFFICER,POLICE,F,Salary,,"$96,060.00 ",\r\n"ADAMS,  DAVID E",SPECIAL EVENTS COORD III,CULTURAL AFFAIRS,F,Salary,,"$85,008.00 ",\r\n"ADAMS,  DEANIE M",LIBRARIAN II,PUBLIC LIBRARY,F,Salary,,"$62,364.00 ",\r\n"ADAMS,  DELRICE ",PUBLIC HEALTH ADMINISTRATOR III,HEALTH,F,Salary,,"$66,984.00 ",\r\n"ADAMS,  DENIS H",CLINICAL THERAPIST III,POLICE,F,Salary,,"$100,776.00 ",\r\n"ADAMS,  DWAYNE D",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ADAMS,  ERWIN ",ASPHALT LABORER,TRANSPORTN,F,Hourly,40,,$40.20 \r\n"ADAMS,  EULA M",DATA ENTRY OPERATOR,WATER MGMNT,F,Salary,,"$53,076.00 ",\r\n"ADAMS,  FREDERICK L",POLICE ADMINISTRATIVE CLERK,POLICE,F,Salary,,"$38,376.00 ",\r\n"ADAMS,  GARY W",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"ADAMS,  GREGORY M",AVIATION SECURITY OFFICER,AVIATION,F,Salary,,"$63,756.00 ",\r\n"ADAMS,  GREGORY W",ADMINISTRATIVE ASST III,BUSINESS AFFAIRS,F,Salary,,"$76,932.00 ",\r\n"ADAMS,  JAIRUS ",POLICE OFFICER,POLICE,F,Salary,,"$48,078.00 ",\r\n"ADAMS,  JAMES W",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$100,980.00 ",\r\n"ADAMS JR,  JERRY M",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ADAMS JR,  JOHN W",FIREFIGHTER-EMT,FIRE,F,Salary,,"$89,148.00 ",\r\n"ADAMSKI,  JERRY J",FIREFIGHTER-EMT (RECRUIT),FIRE,F,Salary,,"$68,616.00 ",\r\n"ADAMSKI,  ROBERT ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"ADAMS,  KRYSTA ",GENERAL LABORER - DSS,STREETS & SAN,F,Hourly,40,,$20.12 \r\n"ADAMS,  LEAH ",ACCOUNTING TECHNICIAN II,COMMUNITY DEVELOPMENT,F,Salary,,"$66,948.00 ",\r\n"ADAMS,  MARJORIE E",LIBRARY PAGE,PUBLIC LIBRARY,P,Hourly,20,,$13.15 \r\n"ADAMS,  MATTHEW ",POLICE OFFICER,POLICE,F,Salary,,"$72,510.00 ",\r\n"ADAMS,  MICHAEL A",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$103,932.00 ",\r\n"ADAMS,  MICHAEL J",WATCHMAN,GENERAL SERVICES,F,Hourly,40,,$21.98 \r\n"ADAMS,  OLIVIA I",LEGAL SECRETARY,LAW,F,Salary,,"$84,420.00 ",\r\n"ADAMS,  QUAN R",MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"ADAMS,  RAYMOND B",SR PROCUREMENT SPECIALIST,PROCUREMENT,F,Salary,,"$68,220.00 ",\r\n"ADAMS,  RAYMOND T",LIEUTENANT-EMT,FIRE,F,Salary,,"$114,324.00 ",\r\n"ADAMS,  REGINALD K",PLUMBING INSPECTOR,BUILDINGS,F,Salary,,"$102,510.00 ",\r\n"ADAMS,  ROBERT L",VENTILATION AND FURNACE INSPECTOR,BUILDINGS,F,Salary,,"$96,657.60 ",\r\n"ADAMS,  ROSITA ",CROSSING GUARD - PER CBA,OEMC,P,Hourly,20,,$15.07 \r\n"ADAMS,  RYAN ",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ADAMS,  SHEILA ",GENERAL LABORER - DSS,STREETS & SAN,F,Hourly,40,,$19.50 \r\n"ADAMS,  SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,F,Salary,,"$100,776.00 ",\r\n"ADAMS,  STANLEY ",SUPVSR OF COMPENSATION,BUSINESS AFFAIRS,F,Salary,,"$93,300.00 ",\r\n"ADAMS,  TALMISE ",POOL MOTOR TRUCK DRIVER,STREETS & SAN,P,Hourly,10,,$28.48 \r\n"ADAMS,  TANERA C",CIVIL ENGINEER IV,TRANSPORTN,F,Salary,,"$110,064.00 ",\r\n"ADAMS THOMAS,  CHEEAREASE R",PUBLIC HEALTH ADMINISTRATOR I,HEALTH,F,Salary,,"$76,932.00 ",\r\n"ADAMS,  TIMOTHY J",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$97,440.00 ",\r\n"ADAMS,  VICKY M",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"ADAPON,  NENITA P",ACCOUNTING TECHNICIAN I,FINANCE,F,Salary,,"$60,972.00 ",\r\n"ADCOCK,  DAVID G",POLICE OFFICER / FLD TRNG OFFICER,POLICE,F,Salary,,"$91,338.00 ",\r\n"ADCOCK,  TOMMY W",CONCRETE LABORER,TRANSPORTN,F,Hourly,40,,$40.20 \r\n"ADDANTE,  VINCENZO ",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"ADDISON,  LATASHA D",LIBRARY CLERK,PUBLIC LIBRARY,F,Salary,,"$29,064.00 ",\r\n"ADDISON,  LEWIS ",LIBRARY ASSOCIATE,PUBLIC LIBRARY,F,Salary,,"$69,492.00 ",\r\n"ADEBAYO,  BENJAMIN B",BUILDING/CONSTRUCTION INSPECTOR,BUILDINGS,F,Salary,,"$116,736.00 ",\r\n"ADE,  JAMES P",POLICE OFFICER,POLICE,F,Salary,,"$84,054.00 ",\r\n"ADE,  JAMES P",SERGEANT,POLICE,F,Salary,,"$111,474.00 ",\r\n"ADEKA,  IBILOLA I",SUPERVISING DISEASE CONTROL INVESTIGATOR - EXCL,HEALTH,F,Salary,,"$77,484.00 ",\r\n"ADELAKUN,  NIKTE E",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"ADELIZZI,  JOY A",DEPUTY COMMISSIONER,BUSINESS AFFAIRS,F,Salary,,"$122,592.00 ",\r\n"ADELMAN,  BRUCE E",LEGISLATIVE AIDE,CITY COUNCIL,F,Salary,,"$19,968.00 ",\r\n"ADENI,  MOHAMED K",ACCOUNTANT IV,FINANCE,F,Salary,,"$100,776.00 ",\r\n"ADESANYA,  EMMANUEL S",ENVIRONMENTAL ENGINEER III,HEALTH,F,Salary,,"$104,328.00 ",\r\n"ADEWOLE,  KAREEM A",CONSTRUCTION LABORER,WATER MGMNT,F,Hourly,40,,$40.20 \r\n"ADEYEMO,  HORATIO A",CIVIL ENGINEER III,TRANSPORTN,F,Salary,,"$100,776.00 ",\r\n"ADEYEMO,  MOJIROLA M",PUBLIC HEALTH ADMINISTRATOR I,HEALTH,F,Salary,,"$73,440.00 ",\r\n"ADKINS,  BRITTANY L",ASST CORPORATION COUNSEL,LAW,F,Salary,,"$60,084.00 ",\r\n"ADKINS,  KERRI M",POLICE COMMUNICATIONS OPERATOR I,OEMC,F,Salary,,"$76,752.00 ",\r\n"ADKINS,  MARC D",POLICE OFFICER,POLICE,F,Salary,,"$96,060.00 ",\r\n"ADKINS,  WILLIAM J",FIRE COMMUNICATIONS OPERATOR II,OEMC,F,Salary,,"$95,712.00 ",\r\n"ADLER,  LAURA R",LIBRARY ASSOCIATE - HOURLY,PUBLIC LIBRARY,P,Hourly,20,,$25.10 \r\n"ADLER,  TRACY L",POLICE OFFICER (ASSIGNED AS EVIDENCE TECHNICIAN),POLICE,F,Salary,,"$88,296.00 ",\r\n"ADLESICK JR,  JOSEPH D",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ADOLFIE,  ELIZABETH U",ADMINISTRATIVE ASST III,BUSINESS AFFAIRS,F,Salary,,"$73,440.00 ",\r\n"ADOLFIE JR,  WALTER S",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"ADREANI,  JOHN J",FIRE ENGINEER-EMT,FIRE,F,Salary,,"$103,350.00 ",\r\n"ADRIAN,  CHERI A",SERGEANT,POLICE,F,Salary,,"$111,474.00 ",\r\n"ADRIAN,  JOHN P",ASST CHIEF AIRPORT OPERATIONS SUPVSR,AVIATION,F,Salary,,"$122,280.00 ",\r\n"AFFANEH,  MAHIR A",POLICE OFFICER,POLICE,F,Salary,,"$93,354.00 ",\r\n"AGAR,  BULENT B",CHIEF ENGINEER OF SEWERS,WATER MGMNT,F,Salary,,"$125,316.00 ",\r\n"AGEE,  LAWRENCE ",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"AGIN,  LAURA J",POLICE OFFICER,POLICE,F,Salary,,"$96,060.00 ",\r\n"AGNEW,  ANTONIO E",POOL MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40,,$35.60 \r\n"AGOSTA,  JOSEPH J",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,,"$103,932.00 ",\r\n"AGOSTINELLI,  MICHAEL A",FIREFIGHTER (PER ARBITRATORS AWARD),FIRE,F,Salary,,"$100,980.00 ",\r\n"AGOSTO,  HECTOR I",POLICE OFFICER/EXPLSV DETECT K9 HNDLR,POLICE,F,Salary,,"$91,338.00 ",\r\n"AGREDANO,  MARIO ",BRIDGE OPERATOR,TRANSPORTN,F,Salary,,"$60,972.00 ",\r\n"AGRON,  EDUARDO ",SERGEANT,POLICE,F,Salary,,"$111,474.00 ",\r\n"AGRON,  EDWIN ",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"AGSALUD,  FERNAN S",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"AGSALUD JR,  JUANITO S",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"AGUADA,  GILBERT GLENN ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"AGUAS,  ALEX ",POLICE OFFICER,POLICE,F,Salary,,"$80,016.00 ",\r\n"AGUAYO,  BRAULIO ",FIREFIGHTER-EMT,FIRE,F,Salary,,"$80,868.00 ",\r\n"AGUAYO,  LUIS A",FIREFIGHTER-EMT,FIRE,F,Salary,,"$92,274.00 ",\r\n"AGUET,  PHILLIP R",SENIOR EMERGENCY MANAGEMENT COORD,HEALTH,F,Salary,,"$70,512.00 ",\r\n"AGUIAR,  WILLIAM M",ASST CORPORATION COUNSEL SUPVSR,LAW,F,Salary,,"$111,804.00 ",\r\n"AGUILAR,  ALFREDO ",DISTRICT SUPVSR - GRAFFITI REMOVAL SERVICES,STREETS & SAN,F,Salary,,"$106,416.00 ",\r\n"AGUILAR,  EFRAIN ",SANITATION LABORER,STREETS & SAN,F,Hourly,40,,$36.21 \r\n"AGUILAR,  ELMA M",ANIMAL CARE AIDE I,ANIMAL CONTRL,F,Salary,,"$70,092.00 ",\r\n"AGUILAR,  ESTHER ",COORD OF SPECIAL PROJECTS,HEALTH,F,Salary,,"$93,300.00 ",\r\n"AGUILAR,  EVARISTO P",POOL MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40,,$35.60 \r\n"AGUILAR,  IRENE ",SANITATION CLERK,STREETS & SAN,F,Salary,,"$70,056.00 ",\r\n"AGUILAR,  JESUS D",PARAMEDIC I/C,FIRE,F,Salary,,"$86,748.00 ",\r\n"AGUILAR JR,  ROBERT ",POOL MOTOR TRUCK DRIVER,STREETS & SAN,P,Hourly,10,,$32.04 \r\n"AGUILAR,  JUANITA ",POOL MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40,,$35.60 \r\n"AGUILAR,  JUANITA M",EDITORIAL ASST,CITY CLERK,F,Salary,,"$63,876.00 ",\r\n"AGUILAR,  KARINA D",SERGEANT,POLICE,F,Salary,,"$104,628.00 ",\r\n"AGUILAR,  LOUIS ",SENIOR CLERK-ELECTIONS,BOARD OF ELECTION,F,Salary,,"$51,732.00 ",\r\n"AGUILAR,  LUIS ",POLICE OFFICER,POLICE,F,Salary,,"$90,024.00 ",\r\n"AGUILAR,  RAY R",POLICE OFFICER,POLICE,F,Salary,,"$87,006.00 ",\r\n"AGUILAR,  RICARDO L",ANIMAL CONTROL OFFICER,ANIMAL CONTRL,F,Salary,,"$69,948.00 ",\r\n"AGUILAR,  ROBERT ",MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40,,$35.60 \r\n"AGUILERA,  HORACIO ",POLICE OFF

**2. Read City_of_Chicago_Payroll_Data.csv as a dataframe in pay.**

In [4]:
pay = pd.read_csv('City_of_Chicago_Payroll_Data.csv')

**3. Show first five records in your data.**

In [ ]:
pay.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN

**3. Get the overview of your data.<br>**

In [5]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

Notice that:<br>
`Typical Hours` is the only float type. <br>
`Typical Hours`, `Annual Salary` and `Hourly Rate` have lots of NaN or null values.

**4. How many 'NaN' you have in each column in your data?**<br>
*Hint: use [<code>isnull()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.isnull.html)*

In [6]:
pay.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

**5. Output the statistics for your dataset.**

In [7]:
pay.describe(include='all')

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
count,32658,32658,32658,32658,32658,7883.000000,24775,7883
unique,32350,1095,36,2,2,NaN,1038,167
top,"HERNANDEZ, JUAN C",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",$35.60
freq,5,9393,12973,30676,24775,NaN,2368,1404
mean,NaN,NaN,NaN,NaN,NaN,34.698719,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,9.145553,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN

**6. What are the maximum, minimum and average Typical Hours? (use 'Typical Hours' column)**<br>

In [8]:
print('Max Typical Hours are:', pay['Typical Hours'].max())
print('Min Typical Hours are:', pay['Typical Hours'].min())
print('Mean/Avg Typical Hours are:', pay['Typical Hours'].mean())

Max Typical Hours are: 40.0
Min Typical Hours are: 10.0
Mean/Avg Typical Hours are: 34.69871876189268

**7. How many employees are on salary and how many are working on hourly basis?**<br>
*Hint: Group the data on 'Salary or Hourly' column. Instead of whole dataset, you can take the single column as input as well.*

In [9]:
pay.groupby('Salary or Hourly').count()['Name']

Salary or Hourly
Hourly     7883
Salary    24775
Name: Name, dtype: int64

In [10]:
pay.groupby('Salary or Hourly').count()[['Name']]

                   Name
Salary or Hourly
Hourly             7883
Salary            24775

In [11]:
pay['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    24775
Hourly     7883
Name: count, dtype: int64

**8. Which department has maximum no of employees?**

In [12]:
pay.groupby('Department').count()[['Name']].idxmax()

Name    POLICE
dtype: object

In [13]:
pay.groupby('Department').count().sort_values(by='Name', ascending=False)[['Name']].head(1)

             Name
Department
POLICE      12973

In [14]:
pay['Department'].value_counts().head(1)

Department
POLICE    12973
Name: count, dtype: int64

**9. How many employees are on Salary and how many are on Hourly in the Police department?**

In [15]:
pay[pay['Department'] == 'POLICE'].groupby('Salary or Hourly').count()[['Name']]

                   Name
Salary or Hourly
Hourly               32
Salary            12941

In [16]:
df = pay[pay['Department']=='POLICE']
df['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    12941
Hourly       32
Name: count, dtype: int64

In [17]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

**10. What are the mean, max and min salaries?**<br>
use <code>.str and replace()</code><br>
Create a new column name "Salaries" and separate the number from dollar sign as float .<br>
Hint: [pandas.series.str](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.split.html) and [Stackoverflow link](https://stackoverflow.com/questions/38516481/trying-to-remove-commas-and-dollars-signs-with-pandas-in-python)

In [19]:
pay['Salary'] = pay['Annual Salary'].str.replace('$','', regex=False).str.replace(',','', regex=False).astype(float)

In [20]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,"$48,078.00",NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,"$87,006.00",NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,"$93,354.00",NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,"$115,932.00",NaN,115932.0

In [21]:
print('min Salary :', pay['Salary'].min())
print('max Salary :', pay['Salary'].max())
print('mean Salary :', pay['Salary'].mean())

min Salary : 0.96
max Salary : 300000.0
mean Salary : 87512.78024137235

**11. Find an employee who has the maximum salary.**<br>
Don't use the max number you got above, write a code for general condition. <br>
Try with [<code>idxmax()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html) as well!

In [22]:
pay[pay['Salary'] == pay['Salary'].max()][['Name', 'Salary']]

                  Name    Salary
8310  EVANS,  GINGER S  300000.0

**12. Find an employee who has the minimum salary.**<br>
Use [<code>idxmin()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmin.html) as well!

In [23]:
pay[pay['Salary'] == pay['Salary'].min()][['Name', 'Salary']]

                 Name  Salary
15387  KOCH,  STEVEN     0.96

In [24]:
pay['Salary']

0        107790.0
1        104628.0
2        114324.0
3         76932.0
4        111474.0
           ...
32653     90024.0
32654     48078.0
32655     87006.0
32656     93354.0
32657    115932.0
Name: Salary, Length: 32658, dtype: float64

In [ ]:
pay['Salary'].idxmin()

15387

In [ ]:
pay.iloc[15387]

Name                           KOCH,  STEVEN
Job Titles           ADMINISTRATIVE SECRETARY
Department                     MAYOR'S OFFICE
Full or Part-Time                           F
Salary or Hourly                       Salary
Typical Hours                             NaN
Annual Salary                           $0.96
Hourly Rate                               NaN
Salary                                   0.96
Name: 15387, dtype: object

In [ ]:
pay.iloc[pay['Salary'].idxmin()]['Name']

'KOCH,  STEVEN '

In [ ]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
 8   Salary             24775 non-null  float64
dtypes: float64(2), object(7)
memory usage: 2.2+ MB

In [ ]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0

**13. What are the mean, max and min Hourly Rate?**<br>
use <code>.str and replace()</code><br>
Hint:
Once again, create a new column name "H_Rate" and separate the number from dollar sign as float .<br>

In [ ]:
pay['H_Rate']=pay['Hourly Rate'].str.replace('$', '').astype(float)

In [ ]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

In [ ]:
print('min H_Rate :', pay['H_Rate'].min())
print('max H_Rate :', pay['H_Rate'].max())
print('mean H_Rate :', pay['H_Rate'].mean())

min H_Rate : 2.65
max H_Rate : 96.0
mean H_Rate : 32.86819231257135

**14. How many employees are getting max Hourly Rate?**

In [ ]:
pay[pay['H_Rate']==pay['H_Rate'].max()].count()['Name']

1

**15. Who is getting max Hourly Rate?**

In [ ]:
pay[pay['H_Rate']==pay['H_Rate'].max()]['Name']

14317    JONES,  JOHN W
Name: Name, dtype: object

In [ ]:
pay.iloc[pay['H_Rate'].idxmax()]

Name                 JONES,  JOHN W
Job Titles             PSYCHIATRIST
Department                   HEALTH
Full or Part-Time                 F
Salary or Hourly             Hourly
Typical Hours                  35.0
Annual Salary                   NaN
Hourly Rate                  $96.00
Salary                          NaN
H_Rate                         96.0
Name: 14317, dtype: object

**16. How many employees are earning less than the average Hourly Rate?**

In [ ]:
pay[pay['H_Rate'] < pay['H_Rate'].mean()]   #.count().head(1)

Name    2791
dtype: int64

**17. How many employees are paid hourly and they have full-time job?**

In [ ]:
pay[(pay['Salary or Hourly']=='Hourly') & (pay['Full or Part-Time']=='F')].count()['Name']

5906

In [ ]:
pay[(pay['Hourly Rate'].notnull()) & (pay['Full or Part-Time']=='F')].count()['Full or Part-Time']

5906

**18. Find the full-time employees who are working at hourly rate of $10.00?**

In [ ]:
pay[(pay['Full or Part-Time']=='F') & (pay['H_Rate']==10)] # or (pay['Hourly Rate']=='$10.00')

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
1232,"AYALA JR, JESUS",STUDENT INTERN,HUMAN RESOURCES,F,Hourly,35.0,NaN,$10.00,NaN,10.0
4522,"CERVANTES, BIANCA A",STUDENT INTERN,BUDGET & MGMT,F,Hourly,35.0,NaN,$10.00,NaN,10.0
6476,"DAVILA, ROBERTO A",ALDERMANIC AIDE,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0
16474,"LEVY, ETHAN",CLERK CITY COUNCIL,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0

**19. How many unique Job Titles are there in the data?**

In [ ]:
pay['Job Titles'].nunique()

1095

**20. What was the average Salary of the employees in each department?**

In [ ]:
pay.groupby('Department')[['Salary']].mean()

                             Salary
Department
ADMIN HEARNG           78912.947368
ANIMAL CONTRL          66089.684211
AVIATION               76140.018777
BOARD OF ELECTION      56051.142857
BOARD OF ETHICS        94552.500000
BUDGET & MGMT          93925.395349
BUILDINGS              98864.833534
BUSINESS AFFAIRS       80446.425000
CITY CLERK             69762.439024
CITY COUNCIL           63577.172069
COMMUNITY DEVELOPMENT  88363.257143
COPA                   98784.705882
CULTURAL AFFAIRS       87048.909091
DISABILITIES           82431.724138
DoIT                   99681.029703
FAMILY & SUPPORT       79013.588785
FINANCE                73276.364662
FIRE                   97762.348662
GENERAL SERVICES       83095.528390
HEALTH                 85488.210938
HUMAN RELATIONS        93778.588235
HUMAN RESOURCES        79851.761194
INSPECTOR GEN          84030.666667
IPRA                   94429.285714
LAW                    84582.814404
LICENSE APPL COMM      80568.000000
MAYOR'S OFFICE         96165.512308
OEMC                   73153.778221
POLICE                 87836.025349
POLICE BOARD           86136.000000
PROCUREMENT            83278.243902
PUBLIC LIBRARY         71273.288136
STREETS & SAN          84347.775701
TRANSPORTN             89976.896061
TREASURER              88062.652174
WATER MGMNT            89894.111803

**21. What is the job title of 'AGAR,  BULENT B'?** please note, there are two spaces between AGAR, and BULENT.

In [ ]:
pay[pay['Name']=='AGAR,  BULENT B']['Job Titles']

230    CHIEF ENGINEER OF SEWERS
Name: Job Titles, dtype: object

In [ ]:
name = input("Enter a Name: ")
pay[pay['Name']==name]['Job Titles']

Enter a Name: AGAR,  BULENT B

230    CHIEF ENGINEER OF SEWERS
Name: Job Titles, dtype: object

**22. What are the top most common job titles?**

In [ ]:
pay['Job Titles'].value_counts().head(1)

Job Titles
POLICE OFFICER    9393
Name: count, dtype: int64

**23. How many people have the word 'officer' in their job title? (This is pretty tricky)**

In [ ]:
def find_string(title):
    if 'officer' in title.lower(): #Field_Officer(manager)
        return True
    else:
        return False

In [ ]:
pay['Job Titles'].apply(find_string)

0        False
1        False
2        False
3        False
4        False
         ...
32653     True
32654     True
32655     True
32656     True
32657    False
Name: Job Titles, Length: 32658, dtype: bool

In [ ]:
pay['Job Titles'].apply(find_string).sum()

11101

In [ ]:
sum(pay['Job Titles'].apply(find_string))

In [ ]:
pay[pay['Job Titles'].str.contains('officer', case=False)].count()['Name']

11101

In [ ]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

**24. Save the final dataframe to a csv file**

In [ ]:
pay.to_csv('E:\\store.csv')